import type { Category } from "./types";

const categories: Category[] = [
  { id: "1", name: "DISC PAD & LEVERS", slug: "disc-pad-levers" },
  { id: "2", name: "DISC ASSY", slug: "disc-assy" },
  { id: "3", name: "POWER CONNECTOR (SB 50)", slug: "power-connector-sb-50" },
  { id: "4", name: "POWER CONNECTOR (IEC & XTs)", slug: "power-connector-iec-xts" },
  { id: "5", name: "POWER CONNECTOR (CHOKARI)", slug: "power-connector-chokari" },
  { id: "6", name: "XLRs & CHARGING CABLES", slug: "xlrs-charging-cables" },
  { id: "7", name: "SILICON CABLES", slug: "silicon-cables" },
  { id: "8", name: "THROTTLES COMMON", slug: "throttles-common" },
  { id: "9", name: "THROTTLES PREMIUM", slug: "throttles-premium" },
  { id: "10", name: "BULBS & LIGHTS", slug: "bulbs-lights" },
  { id: "11", name: "SPEEDOMETER", slug: "speedometer" },
  { id: "12", name: "GLASS", slug: "glass" },
  { id: "13", name: "LINERS & BRAKE CABLES", slug: "liners-brake-cables" },
  { id: "14", name: "BODY PARTS", slug: "body-parts" },
  { id: "15", name: "MOTOR & ACCESSORIES", slug: "motor-accessories" },
  { id: "16", name: "CONTROLLER", slug: "controller" },
  { id: "17", name: "EV CONVERSION KIT", slug: "ev-conversion-kit" },
  { id: "25", name: "CONVERTOR & TRANSVERTOR", slug: "convertor-transvertor" },
  { id: "26", name: "MIRRORS", slug: "mirrors" },
  { id: "27", name: "BALL RACER & BEARING", slug: "ball-racer-bearing" },
  { id: "28", name: "ESS CONNECTOR", slug: "ess-connector" },
  { id: "29", name: "ECYCLE PARTS", slug: "ecycle-parts" },
  { id: "30", name: "FLASHER MCB & COUPLER", slug: "flasher-mcb-coupler" },
  { id: "31", name: "FOOTRESTS & IRON PARTS", slug: "footrests-iron-parts" },
  { id: "34", name: "HANDLE TEE", slug: "handle-tee" },
  { id: "35", name: "SUSPENSION REAR", slug: "suspension-rear" },
  { id: "36", name: "IG LOCK", slug: "ig-lock" },
  { id: "37", name: "OIL SEALS", slug: "oil-seals" },
  { id: "38", name: "SEAT COVERS", slug: "seat-covers" },
  { id: "39", name: "SWITCHES", slug: "switches" },
  { id: "40", name: "TAPES & PAINTS", slug: "tapes-paints" },
  { id: "41", name: "GREASE", slug: "grease" },
  { id: "42", name: "TYRES", slug: "tyres" },
  { id: "43", name: "EV CELL", slug: "ev-cell" },
  { id: "44", name: "BATTERY METAL BOX", slug: "battery-metal-box" },
  { id: "45", name: "BMS LFP DALY", slug: "bms-lfp-daly" },
  { id: "46", name: "BMS DALY NMC", slug: "bms-daly-nmc" },
  { id: "47", name: "BMS LFP JBD", slug: "bms-lfp-jbd" },
  { id: "48", name: "BMS NMC JBD", slug: "bms-nmc-jbd" },
  { id: "49", name: "BATTERY ACCESSORIES", slug: "battery-accessories" },
  { id: "50", name: "DK MACHINES", slug: "dk-machines" },
  { id: "51", name: "SUNKKO MACHINES", slug: "sunkko-machines" },
  { id: "52", name: "TESTING MACHINE", slug: "testing-machine" },
  { id: "53", name: "MOSFETS & ICS", slug: "mosfets-ics" },
  { id: "54", name: "EPOXY RESIN BOARD", slug: "epoxy-resin-board" },
  { id: "55", name: "HST (HEAT SHRINK TUBE)", slug: "hst-heat-shrink-tube" },
  { id: "56", name: "INSULATION PAPER", slug: "insulation-paper" },
  { id: "57", name: "NICKEL PLATED", slug: "nickel-plated" },
  { id: "58", name: "PVC", slug: "pvc" },
];

export default categories; 