import type { Category, Product } from "./types"

export const categories: Category[] = [
  { id: "1", name: "DISC PAD & LEVERS", slug: "disc-pad-levers" },
  { id: "2", name: "DISC ASSY", slug: "disc-assy" },
  { id: "3", name: "POWER CONNECTOR (SB 50)", slug: "power-connector-sb-50" },
  { id: "4", name: "POWER CONNECTOR (IEC & XTs)", slug: "power-connector-iec-xts" },
  { id: "5", name: "POWER CONNECTOR (CHOKARI)", slug: "power-connector-chokari" },
  { id: "6", name: "XLRs & CHARGING CABLES", slug: "xlrs-charging-cables" },
  { id: "7", name: "SILICON CABLES", slug: "silicon-cables" },
  { id: "8", name: "THROTTLES COMMON", slug: "throttles-common" },
  { id: "9", name: "THROTTLES PREMIUM", slug: "throttles-premium" },
  { id: "10", name: "BULBS & LIGHTS", slug: "bulbs-lights" },
  { id: "11", name: "SPEEDOMETER", slug: "speedometer" },
  { id: "12", name: "GLASS", slug: "glass" },
  { id: "13", name: "LINERS & BRAKE CABLES", slug: "liners-brake-cables" },
]

export const products: Product[] = [
  {
    id: "1",
    name: "DISC PAD [DP01 COMMON] (+GST 28%)",
    code: "(04e0)",
    price: 25.9,
    unit: "SET",
    image: "/placeholder.svg?height=200&width=200",
    category: "disc-pad-levers",
    minimumQuantity: 10,
    inStock: true,
  },
  {
    id: "2",
    name: "DISC PAD [DP101 HEAVY] (+GST 28%)",
    code: "(0e55)",
    price: 49.9,
    unit: "SET",
    image: "/placeholder.svg?height=200&width=200",
    category: "disc-pad-levers",
    minimumQuantity: 5,
    inStock: true,
  },
  {
    id: "3",
    name: "DISC PAD [DP02] (+GST 28%)",
    code: "(04dd)",
    price: 49.9,
    unit: "SET",
    image: "/placeholder.svg?height=200&width=200",
    category: "disc-pad-levers",
    minimumQuantity: 5,
    inStock: false,
  },
  {
    id: "4",
    name: "[CHARGER TESTER] (+GST 18%)",
    code: "(1c1e)",
    price: 399,
    unit: "PCS",
    image: "/placeholder.svg?height=200&width=200",
    category: "power-connector-sb-50",
    minimumQuantity: 1,
    inStock: true,
  },
  {
    id: "5",
    name: "[IMP 67.2V+6A] LITHIUM CHARGER (+GST 5%)",
    code: "(0268)",
    price: 1025,
    unit: "PCS",
    image: "/placeholder.svg?height=200&width=200",
    category: "xlrs-charging-cables",
    minimumQuantity: 1,
    inStock: true,
  },
  {
    id: "6",
    name: "13 INCH HYDRAULIC BLUE CAP",
    code: "(s001)",
    price: 899,
    unit: "PAIR",
    image: "/placeholder.svg?height=200&width=200",
    category: "disc-assy",
    minimumQuantity: 1,
    inStock: true,
  },
  {
    id: "7",
    name: "12 INCH ADJUSTABLE BLK INDIAN",
    code: "(s002)",
    price: 799,
    unit: "PAIR",
    image: "/placeholder.svg?height=200&width=200",
    category: "disc-assy",
    minimumQuantity: 1,
    inStock: true,
  },
  {
    id: "8",
    name: "12 INCH ADJUSTABLE WHITE INDIAN",
    code: "(s003)",
    price: 799,
    unit: "PAIR",
    image: "/placeholder.svg?height=200&width=200",
    category: "disc-assy",
    minimumQuantity: 1,
    inStock: true,
  },
  {
    id: "9",
    name: "12 INCH ADJUSTABLE GRN INDIAN",
    code: "(s004)",
    price: 799,
    unit: "PAIR",
    image: "/placeholder.svg?height=200&width=200",
    category: "disc-assy",
    minimumQuantity: 1,
    inStock: true,
  },
  {
    id: "10",
    name: "OKIWAWA INDIAN",
    code: "(s005)",
    price: 899,
    unit: "PAIR",
    image: "/placeholder.svg?height=200&width=200",
    category: "disc-assy",
    minimumQuantity: 1,
    inStock: true,
  },
  {
    id: "11",
    name: "OALA INDIAN",
    code: "(s006)",
    price: 899,
    unit: "PAIR",
    image: "/placeholder.svg?height=200&width=200",
    category: "disc-assy",
    minimumQuantity: 1,
    inStock: true,
  },
  {
    id: "12",
    name: "15 INCH DOUBLE SPRING",
    code: "(s007)",
    price: 999,
    unit: "PAIR",
    image: "/placeholder.svg?height=200&width=200",
    category: "disc-assy",
    minimumQuantity: 1,
    inStock: true,
  },
  {
    id: "13",
    name: "13 INCH ORANGE LINE",
    code: "(s008)",
    price: 899,
    unit: "PAIR",
    image: "/placeholder.svg?height=200&width=200",
    category: "disc-assy",
    minimumQuantity: 1,
    inStock: true,
  },
  {
    id: "14",
    name: "LOADER 10.5 INCH BLK",
    code: "(s009)",
    price: 799,
    unit: "PAIR",
    image: "/placeholder.svg?height=200&width=200",
    category: "disc-assy",
    minimumQuantity: 1,
    inStock: true,
  },
  {
    id: "15",
    name: "E1] EV Lead Acid Charger (Low Cost)",
    code: "(c001)",
    price: 399,
    unit: "PCS",
    image: "/placeholder.svg?height=200&width=200",
    category: "xlrs-charging-cables",
    minimumQuantity: 1,
    inStock: true,
  },
  {
    id: "16",
    name: "E2] EV Lead Acid Charger (Leaf)",
    code: "(c002)",
    price: 499,
    unit: "PCS",
    image: "/placeholder.svg?height=200&width=200",
    category: "xlrs-charging-cables",
    minimumQuantity: 1,
    inStock: true,
  },
  {
    id: "17",
    name: "E3] EV Lead Acid Charger (Percent)",
    code: "(c003)",
    price: 599,
    unit: "PCS",
    image: "/placeholder.svg?height=200&width=200",
    category: "xlrs-charging-cables",
    minimumQuantity: 1,
    inStock: true,
  },
  {
    id: "18",
    name: "E4] EV Lead Acid Charger (Pulse)",
    code: "(c004)",
    price: 699,
    unit: "PCS",
    image: "/placeholder.svg?height=200&width=200",
    category: "xlrs-charging-cables",
    minimumQuantity: 1,
    inStock: true,
  },
]
